### PR TITLE
Only add test suite failure when there is no test case failure

### PR DESCRIPTION
**Pull request by randing89**

### CODE REVIEW

**Comment by FabricioMatteMassive** [comment]
Can we have this merged and published?

My company builds several projects in Bamboo, we are migrating to Jest and this package is really good! Just needs this small fix to be 💯%

**Comment by randing89** [comment]
Can we get this PR merged? Thanks

**Comment by randing89** [comment]
Thanks for merging this PR. 
Can you also release a new version? 

Cheers

**Comment by mdmsua** [comment]
@randing89 released couple of minutes ago as [1.2.1](https://www.npmjs.com/package/jest-bamboo-reporter/v/1.2.1)

**Comment by randing89** [comment]
Nice. Thanks!

**Comment by mdmsua** [comment]
Thanks for fixing it

**Pull request merged**
